server:
  error:
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime
    username: yadnyesh
    password: yadnyesh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
