server:
  error:
    include-stacktrace: always

spring:
  application:
    name: springboot2-essentials
  datasource:
    url: jdbc:mysql://localhost:3306/anime
    username: yadnyesh
    password: yadnyesh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: Spring Boot 2 Essentials
  website: http://devdojo.academy
  github: https://github.com/devdojoacademy/springboot2-essentials